server:
  port: 8080
spring:
  application:
    name: simple-boot-demo
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:simpledb
    username: root
    password: 123456
  h2:
    console:
      enabled: false