server:
  port: 8080
spring:
  application:
    name: simple-boot-demo
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:simpledb
    username: root
    password: 123456
  h2:
    console:
      enabled: false
logging:
  file:
    name: C:/simple-logs/simple-boot-demo.log
    max-size: 100KB
    max-history: 7
    total-size-cap: 0MB
  level: # level是个map，配置不同的日志名称的级别
    root: error
    org.springframework: info
#  config: classpath:demo-logback.xml