server:
  port: 8080
spring:
  application:
    name: simple-boot-mysql-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari: # 连接池配置
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: select 1;
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    placeholder-prefix: "${"
    table: flyway_schema_history
    locations: classpath:db/migration