DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	birth timestamp NULL DEFAULT NULL COMMENT '生日',
	email VARCHAR(200) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);